name: Trigger Rank Repository Workflow

on:
  push:
    branches: [ "master" ]

jobs:
  trigger-rank-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Rank Repository Workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'PANG2OPPA',
              repo: 'github-programmers-rank',
              workflow_id: 'github-programmers-rank.yml',
              ref: 'master'
            })
